{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    # Generated by nixos-generate-config on the target machine at install time.
    # NOT committed to git (it's machine-specific).
    ./hardware-configuration.nix
  ];

  ###########################################################################
  # Boot loader: systemd-boot (UEFI).
  # Windows lives on its own ESP on the 2TB disk. Choose OS via F11 in BIOS.
  ###########################################################################
  boot.loader = {
    systemd-boot = {
      enable = true;
      configurationLimit = 20;
      consoleMode = "max";
    };
    efi.canTouchEfiVariables = true;
    timeout = 3;
  };

  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelParams = [
    "nvidia-drm.modeset=1"
    "nvidia-drm.fbdev=1"
  ];

  ###########################################################################
  # Filesystem / disks
  ###########################################################################
  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly";
    fileSystems = [ "/" ];
  };
  services.fstrim.enable = true;

  ###########################################################################
  # Network / hostname
  ###########################################################################
  networking.hostName = "nixos";
  networking.networkmanager.enable = true;
  networking.firewall.enable = true;

  ###########################################################################
  # Locale: en_US system, ru as input only. Timezone auto via geoclue.
  ###########################################################################
  services.geoclue2.enable = true;
  services.automatic-timezoned.enable = true;
  time.timeZone = null;

  i18n.defaultLocale = "en_US.UTF-8";
  i18n.supportedLocales = [
    "en_US.UTF-8/UTF-8"
    "ru_RU.UTF-8/UTF-8"
    "C.UTF-8/UTF-8"
  ];
  console.keyMap = "us";

  ###########################################################################
  # Users + shell + doas
  ###########################################################################
  users.users.kirnik233899 = {
    isNormalUser = true;
    description = "Kirill";
    extraGroups = [ "wheel" "networkmanager" "video" "audio" "input" "render" "kvm" "libvirtd" ];
    shell = pkgs.zsh;
    # Set password with `passwd kirnik233899` after the first boot.
  };
  programs.zsh.enable = true;

  security.sudo.enable = false;
  security.doas = {
    enable = true;
    extraRules = [{
      users = [ "kirnik233899" ];
      keepEnv = true;
      persist = true;
    }];
  };

  ###########################################################################
  # NVIDIA RTX 4080 — open kernel module, stable userspace.
  ###########################################################################
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    open = true;
    modesetting.enable = true;
    powerManagement.enable = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  ###########################################################################
  # Audio: PipeWire + WirePlumber
  ###########################################################################
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    jack.enable = true;
    wireplumber.enable = true;
  };

  ###########################################################################
  # Bluetooth
  ###########################################################################
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
  services.blueman.enable = true;

  ###########################################################################
  # niri compositor + greetd login
  ###########################################################################
  programs.niri.enable = true;
  services.xserver.enable = false;

  xdg.portal = {
    enable = true;
    extraPortals = with pkgs; [
      xdg-desktop-portal-gtk
      xdg-desktop-portal-gnome
    ];
    config.common.default = [ "gtk" ];
  };

  services.greetd = {
    enable = true;
    settings.default_session = {
      command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --remember --cmd niri-session";
      user = "greeter";
    };
  };

  security.polkit.enable = true;
  services.gnome.gnome-keyring.enable = true;
  programs.dconf.enable = true;
  services.dbus.enable = true;
  services.gvfs.enable = true;
  services.tumbler.enable = true;

  programs.thunar = {
    enable = true;
    plugins = with pkgs.xfce; [ thunar-archive-plugin thunar-volman ];
  };

  ###########################################################################
  # Fonts
  ###########################################################################
  fonts = {
    packages = with pkgs; [
      nerd-fonts.jetbrains-mono
      inter
      noto-fonts
      noto-fonts-cjk-sans
      noto-fonts-emoji
      noto-fonts-extra
    ];
    fontconfig.defaultFonts = {
      serif     = [ "Noto Serif" ];
      sansSerif = [ "Inter" "Noto Sans" ];
      monospace = [ "JetBrainsMono Nerd Font" ];
      emoji     = [ "Noto Color Emoji" ];
    };
  };

  ###########################################################################
  # Steam + gaming stack
  ###########################################################################
  programs.steam = {
    enable = true;
    remotePlay.openFirewall = true;
    gamescopeSession.enable = true;
    extraCompatPackages = with pkgs; [ proton-ge-bin ];
  };
  programs.gamemode.enable = true;

  ###########################################################################
  # Mullvad
  ###########################################################################
  services.mullvad-vpn = {
    enable = true;
    package = pkgs.mullvad-vpn;
  };

  ###########################################################################
  # Containers: podman + distrobox (for Kali container etc.)
  ###########################################################################
  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
    defaultNetwork.settings.dns_enabled = true;
  };

  ###########################################################################
  # Snapper for /home snapshots
  ###########################################################################
  services.snapper.configs.home = {
    SUBVOLUME = "/home";
    ALLOW_USERS = [ "kirnik233899" ];
    TIMELINE_CREATE = true;
    TIMELINE_CLEANUP = true;
    TIMELINE_LIMIT_HOURLY = "5";
    TIMELINE_LIMIT_DAILY = "7";
    TIMELINE_LIMIT_WEEKLY = "4";
    TIMELINE_LIMIT_MONTHLY = "3";
    TIMELINE_LIMIT_YEARLY = "0";
  };

  ###########################################################################
  # zram swap on top of the disk swap partition
  ###########################################################################
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 25;
  };

  ###########################################################################
  # System packages — all GUI + CLI tools in one place
  ###########################################################################
  nixpkgs.config.allowUnfree = true;

  environment.systemPackages = with pkgs; [
    # Wayland session helpers
    wl-clipboard cliphist grim slurp satty wlogout swww
    swaynotificationcenter hyprlock hypridle fuzzel waybar bemoji

    # File managers / archives
    p7zip unrar zip unzip xarchiver

    # Media / docs
    mpv imv zathura

    # Browser
    firefox

    # Editors
    vim neovim vscodium jetbrains.pycharm-community gnome-text-editor

    # Messengers
    telegram-desktop vesktop

    # Audio / system trays
    pavucontrol networkmanagerapplet

    # Gaming
    mangohud lutris bottles heroic gamescope vkbasalt goverlay
    protontricks winetricks wineWowPackages.staging

    # Containers
    distrobox

    # CLI: modern replacements
    eza bat du-dust duf fd ripgrep fzf zoxide

    # CLI: monitoring
    btop htop lm_sensors smartmontools

    # CLI: git / dev
    git lazygit delta tmux

    # CLI: network / download
    curl wget aria2 rsync

    # CLI: misc useful
    tree file pciutils usbutils inxi parted gptfdisk nvme-cli playerctl
  ];

  programs.starship.enable = true;
  programs.fzf.keybindings = true;
  programs.fzf.fuzzyCompletion = true;

  ###########################################################################
  # Nix settings: flakes, GC, binary caches
  ###########################################################################
  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;
      trusted-users = [ "root" "kirnik233899" ];

      substituters = [
        "https://cache.nixos.org"
        "https://nix-community.cachix.org"
        "https://niri.cachix.org"
      ];
      trusted-public-keys = [
        "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
        "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
        "niri.cachix.org-1:Wv0OmO7PsuocRKzfDoJ3mulSl7Z6oezYhGhR+3W2964="
      ];
    };
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 14d";
    };
  };

  system.stateVersion = "25.11";
}
